### ISSUE TITLE
Not installable with yarn install, got this message

### ISSUE THREAD

**Issue by jstam89** [strapi-community/strapi-plugin-measurement-protocol#1]
error strapi-plugin-measurement-protocol@1.0.1: The engine "node" is incompatible with this module. Expected version ">=14.x.x <=16.x.x". Got "12.22.2"

**Comment by Eventyret** [comment]
You will need to have node 14+ to run it using 12 won't work

**Comment by jstam89** [comment]
upgraded to 14 but now getting errors

```
root@js-forge-01:/opt/api_groenerewoning# sudo npm install -g node-gyp
/usr/local/bin/node-gyp -> /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js
+ node-gyp@9.0.0
added 90 packages from 32 contributors in 8.115s
root@js-forge-01:/opt/api_groenerewoning# sudo yarn add strapi-plugin-measurement-protocol
yarn add v1.22.11
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@strapi/plugin-seo > eslint-plugin-react-hooks@4.4.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0-0".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.1.7" has unmet peer dependency "formik@^2.2.6".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.1.7" has unmet peer dependency "immer@9.0.6".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.1.7" has unmet peer dependency "qs@6.10.1".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.1.7" has unmet peer dependency "react-select@^4.0.2".
warning "@strapi/plugin-users-permissions > grant-koa@5.4.8" has unmet peer dependency "koa@>=2.0.0".
warning "@strapi/plugin-users-permissions > react-redux@7.2.3" has unmet peer dependency "redux@^2.0.0 || ^3.0.0 || ^4.0.0-0".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin > mini-css-extract-plugin@2.4.4" has unmet peer dependency "webpack@^5.0.0".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin > styled-components@5.3.5" has unmet peer dependency "react-is@>= 16.8.0".
warning "@strapi/strapi > @strapi/admin > react-virtualized@9.22.3" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha".
warning "@strapi/strapi > @strapi/admin > react-virtualized@9.22.3" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
warning " > strapi-plugin-transformer@2.0.0" has unmet peer dependency "lodash@^4.17.21".
warning " > strapi-plugin-transformer@2.0.0" has unmet peer dependency "yup@^0.32.9".
warning Workspaces can only be enabled in private projects.
[5/5] Building fresh packages...
[11/11] ⡀ @strapi/strapi
[10/11] ⡀ sqlite3
[-/11] ⡀ waiting...
[-/11] ⡀ waiting...
error /opt/api_groenerewoning/node_modules/sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /opt/api_groenerewoning/node_modules/sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@14.17.6 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/opt/api_groenerewoning/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-linux-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-linux-x64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@14.17.6 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-linux-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.17.6 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.17.6 | linux | x64
gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/api_groenerewoning/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/14.17.6/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.17.6',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.17.6/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/opt/api_groenerewoning/node_modules/sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.17.6 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/opt/api_groenerewoning/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c
/bin/sh: 1: python: not found
make: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c] Error 127
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.0-105-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/opt/api_groenerewoning/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/opt/api_groenerewoning/node_modules/sqlite3/lib/binding/node-v83-linux-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /opt/api_groenerewoning/node_modules/sqlite3
gyp ERR! node -v v14.17.6
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
make: Leaving directory '/opt/api_groenerewoning/node_modules/sqlite3/build'
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/api_groenerewoning/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/opt/api_groenerewoning/node_modules/sqlite3/lib/binding/node-v83-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/api_groenerewoning/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.4.0-105-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/opt/api_groenerewoning/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /opt/api_groenerewoning/node_modules/sqlite3
node-pre-gyp ERR! node -v v14.17.6
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
```

**Comment by stafyniaksacha** [comment]
Hello @jstam89 
It seems that you need to install `build-essential` package (`apt install build-essential`)

**Comment by jstam89** [comment]
@stafyniaksacha how do you know, can you tell me a bit more? My whole strapi project is messed up and the admin panel is not accesible anymore, getting 502 errors even after restoring a backup. 

Edit: build-essentials already installed to latest version

**Comment by stafyniaksacha** [comment]
The error you got is not related to this plugin but to `sqlite3`, which need to be build by `node-gyp` (which is the official tool for compiling native addon modules for Node.js).

```
make: Leaving directory '/opt/api_groenerewoning/node_modules/sqlite3/build'
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/api_groenerewoning/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/opt/api_groenerewoning/node_modules/sqlite3/lib/binding/node-v83-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
```

`node-gyp` requires Python / C/C++ compiler as stand here: https://github.com/nodejs/node-gyp#installation

**Comment by stafyniaksacha** [comment]
If you just upgraded your node version, you should try to remove the `node_modules` directory, then reinstall packages

**Comment by jstam89** [comment]
Did not do the job, I keep getting the above error when installing.

Tried removeing the .lock files and node_modules and both with yarn and npm

**Comment by jstam89** [comment]
@stafyniaksacha Looked like my sqlite3 version was not compatible. I had it running on 3.x.x and now upgraded to 5.x.x and the installation succeeded.

**Comment by stafyniaksacha** [comment]
> @stafyniaksacha Looked like my sqlite3 version was not compatible. I had it running on 3.x.x and now upgraded to 5.x.x and the installation succeeded.

If you are running with latest strapi v4, you can replace `sqlite3` with [`better-sqlite3`](https://github.com/JoshuaWise/better-sqlite3)!

**Comment by jstam89** [comment]
@stafyniaksacha thnx! will investigate that. thnx for being here to response.

**Comment by derrickmehaffy** [comment]
I do also 2nd @stafyniaksacha though if you are on a debian based distro you need the `build-essential` package.
